language: ruby
rvm:
        - 2.4.0
addons:
        postgresql: "9.6"
notifications:
        email: false
script: bundle exec rails test -b
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.3
        - cd test/dummy
        - psql -c 'CREATE DATABASE jn316gen_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - sed -e "s/^SET lock_timeout.*//g;^SET idle_in_transaction_session_timeout.*//g;s/^SET row_security.*//g" db/structure.sql.conlock >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices
        - cd ../..

